// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BSERVERPROTOCOL_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_BSERVERPROTOCOL_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {

struct RequestAttack;
struct RequestAttackBuilder;

struct ResponseAttack;
struct ResponseAttackBuilder;

struct RequestAttack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RequestAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQUEST_STRING = 4
  };
  const flatbuffers::String *request_string() const {
    return GetPointer<const flatbuffers::String *>(VT_REQUEST_STRING);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REQUEST_STRING) &&
           verifier.VerifyString(request_string()) &&
           verifier.EndTable();
  }
};

struct RequestAttackBuilder {
  typedef RequestAttack Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_request_string(flatbuffers::Offset<flatbuffers::String> request_string) {
    fbb_.AddOffset(RequestAttack::VT_REQUEST_STRING, request_string);
  }
  explicit RequestAttackBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RequestAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RequestAttack>(end);
    return o;
  }
};

inline flatbuffers::Offset<RequestAttack> CreateRequestAttack(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> request_string = 0) {
  RequestAttackBuilder builder_(_fbb);
  builder_.add_request_string(request_string);
  return builder_.Finish();
}

inline flatbuffers::Offset<RequestAttack> CreateRequestAttackDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *request_string = nullptr) {
  auto request_string__ = request_string ? _fbb.CreateString(request_string) : 0;
  return Protocol::CreateRequestAttack(
      _fbb,
      request_string__);
}

struct ResponseAttack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ResponseAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESPONSE_STRING = 4
  };
  const flatbuffers::String *response_string() const {
    return GetPointer<const flatbuffers::String *>(VT_RESPONSE_STRING);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RESPONSE_STRING) &&
           verifier.VerifyString(response_string()) &&
           verifier.EndTable();
  }
};

struct ResponseAttackBuilder {
  typedef ResponseAttack Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_response_string(flatbuffers::Offset<flatbuffers::String> response_string) {
    fbb_.AddOffset(ResponseAttack::VT_RESPONSE_STRING, response_string);
  }
  explicit ResponseAttackBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ResponseAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ResponseAttack>(end);
    return o;
  }
};

inline flatbuffers::Offset<ResponseAttack> CreateResponseAttack(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> response_string = 0) {
  ResponseAttackBuilder builder_(_fbb);
  builder_.add_response_string(response_string);
  return builder_.Finish();
}

inline flatbuffers::Offset<ResponseAttack> CreateResponseAttackDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *response_string = nullptr) {
  auto response_string__ = response_string ? _fbb.CreateString(response_string) : 0;
  return Protocol::CreateResponseAttack(
      _fbb,
      response_string__);
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_BSERVERPROTOCOL_PROTOCOL_H_
