// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOLBASE_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOLBASE_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

#include "AServerProtocol_generated.h"
#include "BServerProtocol_generated.h"

namespace Protocol {

struct Message;
struct MessageBuilder;

enum MessageType : uint8_t {
  MessageType_NONE = 0,
  MessageType_RequestSomeThing = 1,
  MessageType_ResponseSomThing = 2,
  MessageType_RequestAttack = 3,
  MessageType_ResponseAttack = 4,
  MessageType_MIN = MessageType_NONE,
  MessageType_MAX = MessageType_ResponseAttack
};

inline const MessageType (&EnumValuesMessageType())[5] {
  static const MessageType values[] = {
    MessageType_NONE,
    MessageType_RequestSomeThing,
    MessageType_ResponseSomThing,
    MessageType_RequestAttack,
    MessageType_ResponseAttack
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[6] = {
    "NONE",
    "RequestSomeThing",
    "ResponseSomThing",
    "RequestAttack",
    "ResponseAttack",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (flatbuffers::IsOutRange(e, MessageType_NONE, MessageType_ResponseAttack)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

template<typename T> struct MessageTypeTraits {
  static const MessageType enum_value = MessageType_NONE;
};

template<> struct MessageTypeTraits<Protocol::RequestSomeThing> {
  static const MessageType enum_value = MessageType_RequestSomeThing;
};

template<> struct MessageTypeTraits<Protocol::ResponseSomThing> {
  static const MessageType enum_value = MessageType_ResponseSomThing;
};

template<> struct MessageTypeTraits<Protocol::RequestAttack> {
  static const MessageType enum_value = MessageType_RequestAttack;
};

template<> struct MessageTypeTraits<Protocol::ResponseAttack> {
  static const MessageType enum_value = MessageType_ResponseAttack;
};

bool VerifyMessageType(flatbuffers::Verifier &verifier, const void *obj, MessageType type);
bool VerifyMessageTypeVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  Protocol::MessageType body_type() const {
    return static_cast<Protocol::MessageType>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const Protocol::RequestSomeThing *body_as_RequestSomeThing() const {
    return body_type() == Protocol::MessageType_RequestSomeThing ? static_cast<const Protocol::RequestSomeThing *>(body()) : nullptr;
  }
  const Protocol::ResponseSomThing *body_as_ResponseSomThing() const {
    return body_type() == Protocol::MessageType_ResponseSomThing ? static_cast<const Protocol::ResponseSomThing *>(body()) : nullptr;
  }
  const Protocol::RequestAttack *body_as_RequestAttack() const {
    return body_type() == Protocol::MessageType_RequestAttack ? static_cast<const Protocol::RequestAttack *>(body()) : nullptr;
  }
  const Protocol::ResponseAttack *body_as_ResponseAttack() const {
    return body_type() == Protocol::MessageType_ResponseAttack ? static_cast<const Protocol::ResponseAttack *>(body()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyMessageType(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Protocol::RequestSomeThing *Message::body_as<Protocol::RequestSomeThing>() const {
  return body_as_RequestSomeThing();
}

template<> inline const Protocol::ResponseSomThing *Message::body_as<Protocol::ResponseSomThing>() const {
  return body_as_ResponseSomThing();
}

template<> inline const Protocol::RequestAttack *Message::body_as<Protocol::RequestAttack>() const {
  return body_as_RequestAttack();
}

template<> inline const Protocol::ResponseAttack *Message::body_as<Protocol::ResponseAttack>() const {
  return body_as_ResponseAttack();
}

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_body_type(Protocol::MessageType body_type) {
    fbb_.AddElement<uint8_t>(Message::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Message::VT_BODY, body);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::MessageType body_type = Protocol::MessageType_NONE,
    flatbuffers::Offset<void> body = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyMessageType(flatbuffers::Verifier &verifier, const void *obj, MessageType type) {
  switch (type) {
    case MessageType_NONE: {
      return true;
    }
    case MessageType_RequestSomeThing: {
      auto ptr = reinterpret_cast<const Protocol::RequestSomeThing *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageType_ResponseSomThing: {
      auto ptr = reinterpret_cast<const Protocol::ResponseSomThing *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageType_RequestAttack: {
      auto ptr = reinterpret_cast<const Protocol::RequestAttack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageType_ResponseAttack: {
      auto ptr = reinterpret_cast<const Protocol::ResponseAttack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMessageTypeVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessageType(
        verifier,  values->Get(i), types->GetEnum<MessageType>(i))) {
      return false;
    }
  }
  return true;
}

inline const Protocol::Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<Protocol::Message>(buf);
}

inline const Protocol::Message *GetSizePrefixedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Protocol::Message>(buf);
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Protocol::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Protocol::Message>(nullptr);
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Protocol::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Protocol::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_PROTOCOLBASE_PROTOCOL_H_
